<?php

use Magento\Framework\View\Element\Template;
?>


<ul>
    <li>Tastk 1</li>
    <li>Tastk 1</li>
    <li>Tastk 1</li>
</ul>

<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "todo": {
                        "component": "MageMastery_Todo/js/view/todo",
                        "template": "MageMastery_Todo/todo"
                    }
                }
            }
        }
    }
</script>
