<?php
use Magento\Framework\View\Element\Template;
/** @var Template $block */
?>


<ul>
    <li>Tastk 1</li>
    <li>Tastk 1</li>
    <li>Tastk 1</li>
</ul>

<div data-bind="scope: 'todo'">
    <!-- ko template: getTemplate()--><!-- /ko -->
</div>

<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": <?= $block->getJsLayout(); ?>
        }
    }
</script>
